parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{*Controller.php,DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\UI\Http\Api\Controller\:
        resource: '../src/UI/Http/Api/Controller'
        tags: ['controller.service_arguments']
